apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-app
  labels:
    app: my-app


spec:
  replicas: 10
  selector: 
    matchLabels:
      app: my-app
  
  template:
    metadata: 
      labels: 
        app: my-app

    spec: 

      imagePullSecrets: 
      - name: my-registry-key
      containers:
        - name: my-app
          imagePullPolicy: Always
          image: 730335493644.dkr.ecr.ap-south-1.amazonaws.com/my-app:1.0
          ports:
          - containerPort: 3000