apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment-new
  labels:
    app: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx-newly-created-test
          image: nginx:1.26
          ports:
          - containerPort: 80
